name: holbegram
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.0.5
  cupertino_icons: ^1.0.8
  bottom_navy_bar: ^6.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_launcher_icons: ^0.13.1

  # Firebase
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3
  firebase_database: ^12.1.1
  cloud_firestore: ^6.1.1
  cloudinary_flutter: ^1.3.0

  # Images
  image_picker: ^1.0.7
  http: ^1.2.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/FontsFree-Net-Billabong.ttf

    - family: InstagramSans
      fonts:
        # - asset: assets/fonts/InstagramSans.ttf
