// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2B0be1H37PDEH-MeYtOUMNNrI1OX2ROE',
    appId: '1:330767874776:web:5cd25b8e5ddb9e66cb75ad',
    messagingSenderId: '330767874776',
    projectId: 'holbegram-c7e7c',
    authDomain: 'holbegram-c7e7c.firebaseapp.com',
    storageBucket: 'holbegram-c7e7c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv4ZtinxlPoD9F_9VxSvrfedtLYsxk_ig',
    appId: '1:330767874776:android:f19bb325a406886acb75ad',
    messagingSenderId: '330767874776',
    projectId: 'holbegram-c7e7c',
    storageBucket: 'holbegram-c7e7c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-FNoWEHcXJb6aQz_SkpqfRS9bUnhjHOg',
    appId: '1:330767874776:ios:efa6c8c664948d16cb75ad',
    messagingSenderId: '330767874776',
    projectId: 'holbegram-c7e7c',
    storageBucket: 'holbegram-c7e7c.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-FNoWEHcXJb6aQz_SkpqfRS9bUnhjHOg',
    appId: '1:330767874776:ios:efa6c8c664948d16cb75ad',
    messagingSenderId: '330767874776',
    projectId: 'holbegram-c7e7c',
    storageBucket: 'holbegram-c7e7c.firebasestorage.app',
    iosBundleId: 'com.example.holbegram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2B0be1H37PDEH-MeYtOUMNNrI1OX2ROE',
    appId: '1:330767874776:web:51caa12e7ddc7869cb75ad',
    messagingSenderId: '330767874776',
    projectId: 'holbegram-c7e7c',
    authDomain: 'holbegram-c7e7c.firebaseapp.com',
    storageBucket: 'holbegram-c7e7c.firebasestorage.app',
  );
}
